#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.

# Edit the hosts file
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
sudo sed -i 's/157.240.11.35/8.8.8.8/g' /etc/hosts

# Restart networking to apply changes
sudo service networking restart

